# Generated by Django 3.1.1 on 2020-11-06 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20201009_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'user'},
        ),
    ]
