# Generated by Django 3.1.1 on 2020-10-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank='true', default='employment', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank='true', default='user_name', max_length=20)),
                ('surname', models.CharField(blank='true', default='user_surname', max_length=20)),
                ('age', models.SmallIntegerField(blank='true', default='user_age')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
