# Generated by Django 3.1.1 on 2020-10-09 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_empl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='EmploymentUsers',
        ),
        migrations.AlterModelOptions(
            name='employmentusers',
            options={'verbose_name_plural': 'employment_user'},
        ),
    ]
