# Generated by Django 3.1.1 on 2020-10-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_auto_20201009_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmploymentUsers',
            new_name='Users',
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'user'},
        ),
    ]
