# Generated by Django 3.1.1 on 2020-11-06 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_auto_20201009_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='barcode',
            field=models.BigIntegerField(blank='True', default='2998060398046', max_length=50),
        ),
    ]
