# Generated by Django 3.1.1 on 2020-11-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0004_employment_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='barcode',
            field=models.BigIntegerField(blank='True', default='2998060398046'),
        ),
    ]
