# Generated by Django 3.1.1 on 2020-11-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0005_auto_20201107_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='user',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, to='employment.users'),
        ),
    ]
